# Site settings
title: 芸豆 Blog
SEOTitle: jacob的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: jacob1811@163.com
description: "Practice makes perfect."
keyword: "BY, BY Blog, 初永辉的博客, 初永辉, iOS, Apple, js,Angular,ionic"
url: "http://jacob1811.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jacob1811/jacob1811.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "True mastery of any skill takes a lifetime!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     jacob1811
github_username:    jacob1811
facebook_username:  Yonghui Chu
twitter_username:   jacob1324012




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  
  syntax_highlighter: rouge                          # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: jacob1811

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 4e76b7a510281362c846                           #生成的clientID
  clientSecret: 6ecfc450101e8149c09d05ea91c7275c29a101f5    #生成的clientSecret
  repo: jacob1811.github.io    #仓库名称
  owner: jacob1811    #github用户名
  admin: jacob1811
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 60422c3d3035a46d220f9852be5ab7af

# Google Analytics
ga_track_id: 'UA-117920607-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href:  "https://developer.apple.com/"
    },{
        title: "ionic",
        href: "https://ionicframework.com/docs/"
    },{
        title: "Angular4 修仙之路",
        href: "https://segmentfault.com/a/1190000008754631"
    },{
        title: "JS MDN web docs",
        href: "https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects"
    }
]
